class AddCanvasModel {
  String target_audience;
  String customers_using_our_products_or_services;
  String customer_segments;
  String most_important_customers;
  String interacting_with_audience;
  String strengthening_our_relationship_with_them;
  String differentiating_our_relationship_from_competitors;
  String costs_of_building_relationship;
  String raising_awareness_of_our_existence;
  String preferred_communication_methods_of_audience;
  String optimal_communication_methods;
  String cost_effective_delivery_methods;
  String value_proposition_for_audience;
  String problems_of_audience_we_solve;
  String products_offered_to_each_customer_segment;
  String audience_needs_we_fulfill;
  String required_activities_for_our_products;
  String required_activities_for_communication_channels;
  String required_activities_for_audience_relationships;
  String required_activities_for_revenue_generation;
  String resources_required_for_product_development;
  String resources_required_for_customer_relationships;
  String resources_required_for_revenue_generation;
  String key_partners;
  String key_suppliers;
  String key_resources_requested_from_partners;
  String key_activities_executed_by_partners;
  String products_audience_pays_for;
  String current_payment_methods;
  String preferred_payment_methods;
  String revenue_percentage_per_product_for_project;
  String major_costs_for_project;
  String most_costly_key_resources;
  String most_costly_key_activities;

  AddCanvasModel({
    required this.target_audience,
    required this.customers_using_our_products_or_services,
    required this.customer_segments,
    required this.most_important_customers,
    required this.interacting_with_audience,
    required this.strengthening_our_relationship_with_them,
    required this.differentiating_our_relationship_from_competitors,
    required this.costs_of_building_relationship,
    required this.raising_awareness_of_our_existence,
    required this.preferred_communication_methods_of_audience,
    required this.optimal_communication_methods,
    required this.cost_effective_delivery_methods,
    required this.value_proposition_for_audience,
    required this.problems_of_audience_we_solve,
    required this.products_offered_to_each_customer_segment,
    required this.audience_needs_we_fulfill,
    required this.required_activities_for_our_products,
    required this.required_activities_for_communication_channels,
    required this.required_activities_for_audience_relationships,
    required this.required_activities_for_revenue_generation,
    required this.resources_required_for_product_development,
    required this.resources_required_for_customer_relationships,
    required this.resources_required_for_revenue_generation,
    required this.key_partners,
    required this.key_suppliers,
    required this.key_resources_requested_from_partners,
    required this.key_activities_executed_by_partners,
    required this.products_audience_pays_for,
    required this.current_payment_methods,
    required this.preferred_payment_methods,
    required this.revenue_percentage_per_product_for_project,
    required this.major_costs_for_project,
    required this.most_costly_key_resources,
    required this.most_costly_key_activities,
  });
}
