// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGT6HTtXQ_dJgT8IrTc7qT_W-7AxNxBk',
    appId: '1:472892227550:web:8f1afa49ad0fe35c8f674f',
    messagingSenderId: '472892227550',
    projectId: 'grad2024-138a4',
    authDomain: 'grad2024-138a4.firebaseapp.com',
    storageBucket: 'grad2024-138a4.appspot.com',
    measurementId: 'G-XRR55D7V67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwc8flnsQUPR-LpAQhzHBmc5W7e3T4DM',
    appId: '1:472892227550:android:98073fb7f1531cdb8f674f',
    messagingSenderId: '472892227550',
    projectId: 'grad2024-138a4',
    storageBucket: 'grad2024-138a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yqFOqxMZsaxl3vIimkR_cnfyz-1YVcw',
    appId: '1:472892227550:ios:44e5e1fb507083448f674f',
    messagingSenderId: '472892227550',
    projectId: 'grad2024-138a4',
    storageBucket: 'grad2024-138a4.appspot.com',
    iosBundleId: 'com.example.bloomProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_yqFOqxMZsaxl3vIimkR_cnfyz-1YVcw',
    appId: '1:472892227550:ios:44e5e1fb507083448f674f',
    messagingSenderId: '472892227550',
    projectId: 'grad2024-138a4',
    storageBucket: 'grad2024-138a4.appspot.com',
    iosBundleId: 'com.example.bloomProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGT6HTtXQ_dJgT8IrTc7qT_W-7AxNxBk',
    appId: '1:472892227550:web:20bc3f4c580df46e8f674f',
    messagingSenderId: '472892227550',
    projectId: 'grad2024-138a4',
    authDomain: 'grad2024-138a4.firebaseapp.com',
    storageBucket: 'grad2024-138a4.appspot.com',
    measurementId: 'G-TC300Q85ZH',
  );
}
